# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCollection():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_collection(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(1)").send_keys("ccr1")
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(2)").send_keys("Ccr030323!")
    self.driver.find_element(By.CSS_SELECTOR, ".button-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".imgContainer").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-list:nth-child(2) .card-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".interaction-button:nth-child(3) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".interaction-button:nth-child(3) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".interaction-button:nth-child(2) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".interaction-button:nth-child(2) img").click()
  
