# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginRegister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginRegister(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(830, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".change-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(1)").send_keys("LitaZ")
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(2)").send_keys("Ccr030323!")
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(4)").send_keys("2268920184@qq.com")
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-box:nth-child(6)").send_keys("15166217302")
    self.driver.find_element(By.CSS_SELECTOR, ".el-check-tag:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tag-wrapper").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-check-tag:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-check-tag:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-text").click()
  
